# Generated by Django 6.0.6 on 2026-06-25 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('detecting_rooms', 'Detecting rooms'), ('pending_review', 'Pending review'), ('calculating', 'Calculating lighting'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixtureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('luminous_flux_lm', models.FloatField(help_text='Lumen output per fixture')),
                ('max_spacing_to_height_ratio', models.FloatField(default=1.2)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('room_type', models.CharField(choices=[('office', 'Office'), ('bedroom', 'Bedroom'), ('living_room', 'Living room'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('corridor', 'Corridor'), ('classroom', 'Classroom'), ('storage', 'Storage'), ('other', 'Other')], default='other', max_length=30)),
                ('polygon', models.JSONField(help_text='List of [x, y] vertex coordinates, in metres')),
                ('area_sq_m', models.FloatField()),
                ('required_lux', models.FloatField(blank=True, null=True)),
                ('mounting_height_m', models.FloatField(default=2.7)),
                ('confirmed', models.BooleanField(default=False)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='drawings.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Position in metres, same frame as the room polygon')),
                ('y', models.FloatField(help_text='Position in metres, same frame as the room polygon')),
                ('fixture_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drawings.fixturetype')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='drawings.room')),
            ],
        ),
    ]
