# Generated by Django 6.0.6 on 2026-07-02 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='preview_extents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='preview_image',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='fixturetype',
            name='wattage_w',
            field=models.FloatField(default=120, help_text='Wattage per fixture'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('detecting_rooms', 'Detecting rooms'), ('pending_review', 'Pending review'), ('needs_manual_rooms', 'Needs manual room boundaries'), ('calculating', 'Calculating lighting'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=30),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='x',
            field=models.FloatField(help_text='Position in metres'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='y',
            field=models.FloatField(help_text='Position in metres'),
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct_label', models.CharField(max_length=20)),
                ('cct_type', models.CharField(choices=[('lighting', 'Lighting'), ('socket', 'Socket'), ('socket_key', 'Socket Key')], max_length=20)),
                ('phase', models.CharField(max_length=1)),
                ('n_points', models.IntegerField()),
                ('total_load_w', models.FloatField()),
                ('cable_csa_mm2', models.FloatField()),
                ('mcb_rating_a', models.FloatField()),
                ('voltage_drop_v', models.FloatField(default=0.0)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='drawings.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='DB', max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('incomer_mcb_a', models.IntegerField(default=30)),
                ('incoming_cable_csa_mm2', models.FloatField(default=4.0)),
                ('schedule_data', models.JSONField(blank=True, null=True)),
                ('sld_file', models.FileField(blank=True, null=True, upload_to='outputs/sld/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='outputs/reports/')),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_boards', to='drawings.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='SmallPowerPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, default='', max_length=30)),
                ('kind', models.CharField(choices=[('SP', 'Socket Point'), ('SK', 'Socket Key'), ('SW', 'Switch')], max_length=2)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('circuit_no', models.IntegerField(default=0)),
                ('phase', models.CharField(blank=True, default='', max_length=1)),
                ('load_w', models.FloatField(default=150)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_power_points', to='drawings.drawing')),
            ],
        ),
    ]
