# Generated by Django 6.0.7 on 2026-07-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_drawing_preview_extents_drawing_preview_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_fixtures', models.IntegerField(blank=True, null=True)),
                ('required_lux', models.FloatField(blank=True, null=True)),
                ('fixture_type_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override', to='drawings.room')),
            ],
        ),
    ]
